
export const GET_INITIAL_CITY = "GET_INITIAL_CITY";
export const ADD_NEW_CITY = "ADD_NEW_CITY";
export const GET_WEATHER = "GET_WEATHER";
export const GET_CITY_WEATHER = "GET_CITY_WEATHER";
export const REMOVE_CITY = "REMOVE_CITY";
export const INCORRECT_CITY = "INCORRECT_CITY";
export const REMOVE_INCORRECT_CITY = "REMOVE_INCORRECT_CITY";

export type GET_INITIAL_CITY = "GET_INITIAL_CITY";
export type ADD_NEW_CITY = "ADD_NEW_CITY";
export type GET_WEATHER = "GET_WEATHER";
export type GET_CITY_WEATHER = "GET_CITY_WEATHER";
export type REMOVE_CITY = "REMOVE_CITY";
export type INCORRECT_CITY = "INCORRECT_CITY";
export type REMOVE_INCORRECT_CITY = "REMOVE_INCORRECT_CITY";